version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npx playwright install
      - npx playwright install-deps

      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - allure-report/