version: '3'
services:
  playwright-tests:
    image: playwright-tests
    environment:
      -  TEST?=$${TEST}
    command:  >
      /bin/sh -c "npm run $${TEST}; npm run allure:generate ; exit 0"
    volumes:
      - ./app/results:/app/allure-report
      